version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node version:" && node --version
      - echo "NPM version:" && npm --version
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm cache clean --force
      - npm install --verbose
  build:
    commands:
      - echo Building the project...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
